### ISSUE TITLE
Downloading model every test.

### ISSUE THREAD

**Issue by AlvaroCavalcante** [Lucs1590/Nkocr#19]
I noticed that in every test that I run the model is downloaded again. This doesn't happen when running the OCR, only when testing, that's a factor that impacts directly in execution time when testing.

**Comment by AlvaroCavalcante** [comment]
@Lucs1590 I saw this is a test, called "test_get_model", I think it's better to let it without any test because the model has almost 97MB to download every execution.

**Comment by Lucs1590** [comment]
Right, the outcome of this Issue was to divide the tests into folders:

- integration;
- unit;
- fixtures.

And in order not to download an EAST model in all executions, it is enough to standardize the execution of the tests in the unit folder.
To execute via command line, use:
```bash
python3 -m unittest discover -s tests/unit
```

The integration tests will be performed on the GitHub pipelines, but it is worth saying that good practice is always to have tests.

The separation of the tests was done following these criteria:
 - Calling an HTTP REST API;
 - Calling a Python API;
 - Calling a web service;
 - Use model, ANN or similar.

For more details, go to: https://realpython.com/python-testing/#writing-integration-tests
