### ISSUE TITLE
shows file not found when using OcrTable()

### ISSUE THREAD

**Issue by cherry247** [Lucs1590/Nkocr#99]
`text = OcrTable("https://foodnoms.com/static/blog/2020-04-04_better-nutrition-label-scanner/label-scanner.png")`

error: 
`FileNotFoundError                         Traceback (most recent call las`

**Comment by Lucs1590** [comment]
Hi @cherry247 , how are you?

Did you finish all the prerequisites and installation instructions?
I run your url here and got the following result:

![image](https://user-images.githubusercontent.com/38580547/142901999-36049956-b265-4d3c-bb8b-ad12bd201268.png)

Obs.: I didn't change to english language because I was just testing.
